name: helm-deploy
description: "Execute helm package to deploy built image"
inputs:
  image-tag:
    description: "The deploying docker image tag"
    required: true           
          

runs:
  using: composite
  steps:
    - name: debug value file
      id: debug-value-file
      shell: bash
      working-directory: ./deploy/infrastore-chart
      run: |
        pwd
        sed s/%TAG%/${{ inputs.image-tag }}/g values.yaml



