name: helm-deploy
description: "Execute package to deploy"
inputs:
  image-tag:
    description: "The deploying docker image tag"
    required: true

runs:
  using: composite
  steps:
    - name: replace image tag in the value file
      id: set-image-tag
      shell: bash
      run: |
        pwd
        cd deploy/infrastore-chart
        pwd