apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastore
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: infrastore
    name: in-cluster
  project: default
  source:
    path: deploy/infrastore-chart
    repoURL: https://github.com/RamprasadDamodar/new_project
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
