{{- if .Values.persistence.media.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "infrastore-chart.fullname" . }}-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- if .Values.persistence.media.storageClassName }}
  storageClassName: {{ .Values.persistence.media.storageClassName }}
  {{- end }}
{{- end }}
---
{{- if .Values.persistence.db.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "infrastore-chart.fullname" . }}-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}
  {{- if .Values.persistence.db.storageClassName }}
  storageClassName: {{ .Values.persistence.db.storageClassName }}
  {{- end }}
{{- end }}
