name: Update Image Tag

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Enter the new Docker image tag'
        required: true
        default: 'latest'

jobs:
  update_tag:
    runs-on: ubuntu-latest

    steps:
    -   name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

    -   name: Update image tag in values.yaml
        run: |
            cd deploy/infrastore-chart
            echo "Updating image tag to ${{ github.event.inputs.image_tag }}"
            sed -i "s/tag:.*/tag: ${{ github.event.inputs.image_tag }}/" values.yaml

    -   name: Commit and push changes
        run: |
            git config --global user.name "RamprasadDamodar"
            git config --global user.email "Ramprasad.Damodar1989@gmail.com"
            git add .
            git commit -m "Updated image tag to ${{ github.event.inputs.image_tag }}"
            git push
